### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by Haythamasalama** [Haythamasalama/haythamasalama.me#14]
- [x] refactor tailwind config
- [x] pages list
  - [x]  [Tools] make horizontal card component (icon,title,description)
  - [x]  [About] make photo with edit stroy section and title 
  - [x]  [Articles] refactor components
  - [x]  [Projects] refactor code,token
  - [x]  [Projects] make loading component 
  - [x]  [Projects] use card component 
  - [x]  [Project] started project and more actions 
- [x] refactor single article page style  
-  [x] #15
-  [x] #16
